name: release
on:
  push:
    branches:
      - master
jobs:
  release-please:
    name: release-please
    runs-on: ubuntu-latest
    outputs:
      release: ${{ steps.release.outputs.release_created || false }}
    permissions:
      contents: write
      pull-requests: write
    steps:
      - id: release
        uses: googleapis/release-please-action@v4
  publish-package:
    name: publish-package
    runs-on: ubuntu-latest
    needs:
      - release-please
    if: contains(needs.release-please.release, 'true')
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          registry-url: https://registry.npmjs.org
      - run: npm ci
      - run: npm run build
      - run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
